var airQualityData =[
    {
        "unique_id": 410725,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 7.8
    },  {
        "unique_id": 549749,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 18.5
    },  {
        "unique_id": 179441,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 18.7
    },  {
        "unique_id": 742158,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 6.5
    },  {
        "unique_id": 547363,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 7.2
    },  {
        "unique_id": 549755,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 17.9
    },  {
        "unique_id": 179431,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 21.5
    },  {
        "unique_id": 179656,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 9.8
    },  {
        "unique_id": 825807,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 15.4
    },  {
        "unique_id": 179439,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 19.9
    }, {
        "unique_id": 179664,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 8.7
    },  {
        "unique_id": 547357,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 7.5
    },  {
        "unique_id": 179434,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 20.6
    },  {
        "unique_id": 179433,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 21
    },  {
        "unique_id": 667033,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 16
    },  {
        "unique_id": 740883,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 16.7
    },  {
        "unique_id": 643309,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 21.7
    },  {
        "unique_id": 179646,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 10.1
    },  {
        "unique_id": 179426,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 21
    },  {
        "unique_id": 179435,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 28.7
    },  {
        "unique_id": 179440,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 28
    },  {
        "unique_id": 549752,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 24.6
    },  {
        "unique_id": 179660,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 10.9
    },  {
        "unique_id": 179665,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 10.7
    },  {
        "unique_id": 547360,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 8.7
    },  {
        "unique_id": 179645,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 12.6
    },  {
        "unique_id": 740886,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 20
    },  {
        "unique_id": 179430,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 31
    },  {
        "unique_id": 179420,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 33.9
    },  {
        "unique_id": 410728,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 9
    },  {
        "unique_id": 179662,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 8.4
    },  {
        "unique_id": 742161,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 6.2
    },  {
        "unique_id": 549758,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 13.4
    },  {
        "unique_id": 333949,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 7.7
    },  {
        "unique_id": 179432,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 16.2
    },  {
        "unique_id": 179422,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 16.8
    },  {
        "unique_id": 412426,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 13.5
    },  {
        "unique_id": 602699,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 12.9
    },  {
        "unique_id": 410734,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 6.8
    },  {
        "unique_id": 667051,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 11.6
    },  {
        "unique_id": 336481,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 25.2
    },  {
        "unique_id": 667039,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 20.5
    },  {
        "unique_id": 179425,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 30.6
    },  {
        "unique_id": 179657,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 9.4
    },  {
        "unique_id": 179655,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 11.9
    },  {
        "unique_id": 333943,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 10.2
    },  {
        "unique_id": 605654,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 8.5
    },  {
        "unique_id": 179650,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 11.6
    },  {
        "unique_id": 742155,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 7.4
    },  {
        "unique_id": 179658,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 9.5
    },  {
        "unique_id": 179659,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 9
    },  {
        "unique_id": 742149,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 6.6
    },  {
        "unique_id": 742152,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 6.6
    },  {
        "unique_id": 179438,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 19.9
    },  {
        "unique_id": 549746,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 19.4
    },  {
        "unique_id": 740880,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 16.5
    },  {
        "unique_id": 179653,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 10.8
    },  {
        "unique_id": 179643,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 11.1
    },  {
        "unique_id": 333940,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 8.7
    },  {
        "unique_id": 669850,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 6.1
    },  {
        "unique_id": 179429,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 22.8
    },  {
        "unique_id": 179418,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 24.5
    },  {
        "unique_id": 336475,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 20
    },  {
        "unique_id": 412420,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 24.4
    },  {
        "unique_id": 605648,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 7.3
    },  {
        "unique_id": 179437,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 14.5
    },  {
        "unique_id": 825798,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 11.2
    },  {
        "unique_id": 179424,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 22.7
    },  {
        "unique_id": 333937,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 9.2
    },  {
        "unique_id": 669853,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 6.1
    },  {
        "unique_id": 211437,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 10.9
    },  {
        "unique_id": 179654,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 10.2
    },  {
        "unique_id": 179644,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 10.5
    },  {
        "unique_id": 649657,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 6.5
    },  {
        "unique_id": 410731,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 7.2
    },  {
        "unique_id": 643312,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 15.7
    },  {
        "unique_id": 412423,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 17.7
    },  {
        "unique_id": 179661,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 8.6
    },  {
        "unique_id": 179649,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 9.7
    },  {
        "unique_id": 643306,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 16.5
    },  {
        "unique_id": 643303,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 16
    },  {
        "unique_id": 412417,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 18.5
    },  {
        "unique_id": 211435,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 9.3
    },  {
        "unique_id": 547354,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 7.7
    },  {
        "unique_id": 605651,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 7.2
    },  {
        "unique_id": 211390,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 19.8
    },  {
        "unique_id": 211393,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 18.9
    },  {
        "unique_id": 547366,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2017",
        "start_date": "2017-01-01",
        "data_value": 6.8
    },  {
        "unique_id": 179442,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 13.8
    },  {
        "unique_id": 740892,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 12.8
    },  {
        "unique_id": 336487,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 13.7
    },  {
        "unique_id": 740889,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2021",
        "start_date": "2021-01-01",
        "data_value": 15.5
    },  {
        "unique_id": 179421,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 22.2
    },  {
        "unique_id": 211436,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 9.1
    },  {
        "unique_id": 179427,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 15.4
    },  {
        "unique_id": 179666,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 8.4
    },  {
        "unique_id": 211438,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 8.6
    },  {
        "unique_id": 179419,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 24.1
    },  {
        "unique_id": 179428,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2011",
        "start_date": "2010-12-01",
        "data_value": 22.7
    },  {
        "unique_id": 667027,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 17.1
    },  {
        "unique_id": 211439,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 8.4
    },  {
        "unique_id": 211392,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 26.7
    },  {
        "unique_id": 336478,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 19.3
    },  {
        "unique_id": 602693,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 23.4
    },  {
        "unique_id": 669841,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 5.5
    },  {
        "unique_id": 669847,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 7.2
    },  {
        "unique_id": 179651,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 9.2
    },  {
        "unique_id": 333946,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 8.4
    },  {
        "unique_id": 669844,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 6.1
    },  {
        "unique_id": 412414,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 18.4
    },  {
        "unique_id": 602687,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 17.7
    },  {
        "unique_id": 410722,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2016",
        "start_date": "2015-12-31",
        "data_value": 7.8
    },  {
        "unique_id": 179663,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 9.1
    },  {
        "unique_id": 179423,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 22.2
    },  {
        "unique_id": 179652,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 8.8
    },  {
        "unique_id": 649654,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 8.3
    },  {
        "unique_id": 823327,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 5.2
    },  {
        "unique_id": 179647,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2009",
        "start_date": "2008-12-01",
        "data_value": 9.8
    },  {
        "unique_id": 179648,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2010",
        "start_date": "2009-12-01",
        "data_value": 10.1
    },  {
        "unique_id": 211391,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 20
    },  {
        "unique_id": 823330,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 5.7
    },  {
        "unique_id": 179667,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2013",
        "start_date": "2012-12-01",
        "data_value": 8
    },  {
        "unique_id": 649648,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 6.9
    },  {
        "unique_id": 823339,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 6.1
    },  {
        "unique_id": 336484,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2015",
        "start_date": "2015-01-01",
        "data_value": 18.5
    },  {
        "unique_id": 825810,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 1,
        "geo_place_name": "Bronx",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 16
    },  {
        "unique_id": 605660,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 6.4
    },  {
        "unique_id": 605657,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 6.8
    },  {
        "unique_id": 179436,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2012",
        "start_date": "2011-12-01",
        "data_value": 19.4
    },  {
        "unique_id": 667045,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2020",
        "start_date": "2020-01-01",
        "data_value": 14.8
    },  {
        "unique_id": 602696,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 17.2
    },  {
        "unique_id": 602690,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2018",
        "start_date": "2018-01-01",
        "data_value": 17.8
    },  {
        "unique_id": 211394,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2014",
        "start_date": "2013-12-01",
        "data_value": 14.2
    },  {
        "unique_id": 823333,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 7
    },  {
        "unique_id": 649660,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 5.9
    },  {
        "unique_id": 825804,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 3,
        "geo_place_name": "Manhattan",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 19.1
    },  {
        "unique_id": 643315,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 5,
        "geo_place_name":"Staten Island",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 11.9
    },  {
        "unique_id": 825801,
        "indicator_id": 375,
        "name": "Nitrogen dioxide (NO2)",
        "measure_info": "ppb",
        "geo_type_name": "Borough",
        "geo_join_id": 4,
        "geo_place_name": "Queens",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 14.9
    },  {
        "unique_id": 649651,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2019",
        "start_date": "2019-01-01",
        "data_value": 6.7
    },  {
        "unique_id": 823336,
        "indicator_id": 365,
        "name": "Fine particles (PM 2.5)",
        "measure_info": "mcg/m3",
        "geo_type_name": "Borough",
        "geo_join_id": 2,
        "geo_place_name": "Brooklyn",
        "time_period": "Annual Average 2022",
        "start_date": "2022-01-01",
        "data_value": 5.8
    }
];